version: 2.1

jobs:
  deploy-snowflake-changes-job:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: Use Python 3.8.x
          command: |
            echo "Python version: $(python --version)"
      
      - run:
          name: Install schemachange
          command: |
            pip install schemachange

      - run:
          name: Run schemachange
          environment:
            SF_ACCOUNT: $SF_ACCOUNT
            SF_USERNAME: $SF_USERNAME
            SF_ROLE: $SF_ROLE
            SF_WAREHOUSE: $SF_WAREHOUSE
            SF_DATABASE: $SF_DATABASE
            SNOWFLAKE_PASSWORD: $SF_PASSWORD
          command: |
            echo "WORKING_DIRECTORY: $PWD"
            schemachange -f migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE7.CHANGE_HISTORY --create-change-history-table

      - run:
          name: Run schemachange with verbose logging
          command: |
            echo "WORKING_DIRECTORY: $PWD"
            schemachange -f migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE7.CHANGE_HISTORY --create-change-history-table -vvv

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-snowflake-changes-job:
          filters:
            branches:
              only:
                - main
