version: 2.1
orbs:
  python: circleci/python@1.2.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy-snowflake-changes-job

jobs:
  deploy-snowflake-changes-job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
    name: Run schemachange
    command: |
      echo "CIRCLE_WORKING_DIRECTORY: $CIRCLE_WORKING_DIRECTORY"
      python --version
      echo "Step 1: Installing schemachange"
      pip install schemachange

      echo "Step 2: Running schemachange"
      schemachange -c $CIRCLE_WORKING_DIRECTORY/migrations/schemachange.toml -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -p $SNOWFLAKE_PASSWORD --create-change-history-table --root-folder $CIRCLE_WORKING_DIRECTORY/migrations
    environment:
      SF_ACCOUNT: ${SF_ACCOUNT}
      SF_USERNAME: ${SF_USERNAME}
      SF_ROLE: ${SF_ROLE}
      SF_WAREHOUSE: ${SF_WAREHOUSE}
      SF_DATABASE: ${SF_DATABASE}
      SNOWFLAKE_PASSWORD: ${SF_PASSWORD}




            
