version: 2.1

jobs:
  deploy-snowflake-changes-job:
    docker:
      - image: circleci/python:3.8

    environment:
      SF_ACCOUNT: LJYHXDV-HY17256
      SF_USERNAME: DEEPAK
      SF_ROLE: ACCOUNTADMIN
      SF_WAREHOUSE: COMPUTE_WH
      SF_DATABASE: SF_CICD
      SNOWFLAKE_PASSWORD: Deepu@822

    steps:
      - checkout

      - run:
          name: Use Python 3.8.x
          command: |
            echo "Python version: $(python --version)"
      
      - run:
          name: Install schemachange
          command: |
            pip install schemachange

      - run:
          name: Run schemachange
          command: |
            echo "WORKING_DIRECTORY: $PWD"
            schemachange -f migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE21.CHANGE_HISTORY --create-change-history-table


workflows:
  version: 2
  deploy:
    jobs:
      - deploy-snowflake-changes-job:
          filters:
            branches:
              only:
                - main
