version: 2.1

jobs:
  deploy-snowflake-changes-job:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout

      - run:
          name: Print Working Directory
          command: echo "Working Directory: $PWD"

      - run:
          name: Run schemachange
          environment:
            SF_ACCOUNT: $SF_ACCOUNT
            SF_USERNAME: $SF_USERNAME
            SF_ROLE: $SF_ROLE
            SF_WAREHOUSE: $SF_WAREHOUSE
            SF_DATABASE: $SF_DATABASE
            SNOWFLAKE_PASSWORD: $SF_PASSWORD
          command: |
            python --version
            echo "Step 1: Installing schemachange"
            pip install schemachange

            echo "Step 2: Running schemachange"
            schemachange -f $PWD/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-snowflake-changes-job:
          filters:
            branches:
              only:
                - main
          when: on_success
