version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      # Print the current working directory for debugging
      - run:
          name: Print working directory
          command: pwd

      # Change the working directory to the correct path
      - run:
          name: Change working directory
          command: cd migrations

      # Install dependencies or run any setup steps here if needed
      - run:
          name: Install dependencies
          command: |
            pip install schemachange

      # Run schemachange command
      - run:
          name: Run schemachange
          command: |
            schemachange -f migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table

    environment:
      SF_ACCOUNT: ${SF_ACCOUNT}
      SF_USERNAME: ${SF_USERNAME}
      SF_ROLE: ${SF_ROLE}
      SF_WAREHOUSE: ${SF_WAREHOUSE}
      SF_DATABASE: ${SF_DATABASE}
      SNOWFLAKE_PASSWORD: ${SF_PASSWORD}
